
- name: 'install nginx ingress'
  helm_cli:
    release: '{{ nginx_ingress_release_name }}'
    chart:
      name: nginx-ingress
      version: '{{ nginx_ingress_version }}'
      repo: '{{ nginx_ingress_repo }}'
    namespace: '{{ nginx_ingress_namespace }}'
    binary: '/usr/local/bin/'
    values_list:
    - "{{ lookup('file', role_path ~ '/files/nginx_ingress_values.yml') }}"
  register: nginx_helm_install
  run_once: True

- debug:
    var: nginx_helm_install
  run_once: True
  when: debug|bool

- name: 'Enable monitoring of nginx-ingress'
  import_tasks: prometheus_monitoring.yml
  when: nginx_ingress_prometheus_monitoring|bool
