- name: "LVM Setup: Create the LVM Volume Groups"
  lvg:
    pvs: '{{ item.value.drives|join(",") }}'
    vg: '{{ item.key }}'
    state: present
  register: vg_creation
  with_dict: >-
    {
      {%- for vg_name, vg_prop in vg_list.items()
            if vg_prop.drives -%}
        '{{ vg_name }}': {{ vg_prop }},
      {%- endfor -%}
    }

- name: "LVM Setup: Gather fact with LVM data"
  setup:
    gather_subset: 'hardware'
    filter: 'ansible_lvm'
  when: vg_creation is changed
